language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4.2"

sudo: false

cache:
  directories:
  - node_modules

before_install:
  - npm config set strict-ssl false

before_script:
  # we only need to run eslint once per build, so let's conserve a few resources
  - 'if [ "x$TRAVIS_NODE_VERSION" = "x0.12" ]; then $(npm bin)/eslint .; fi'

script:
  - ./scripts/ci-test.sh

git:
  depth: 10
